version: "3"

services:
  wordpress:
    image: wordpress:5.3.2
    restart: always
    volumes: ["./wp-content:/var/www/html/wp-content"]
    environment:
      WORDPRESS_DB_HOST:
      WORDPRESS_DB_USER:
      WORDPRESS_DB_PASSWORD:
      WORDPRESS_DB_NAME:
    ports:
      - 80:80
      - 443:443
